### ISSUE TITLE
Do not add another @Override annotation if one already exists

### ISSUE THREAD

**Issue by MarvinWyrich** [Refactoring-Bot/Refactoring-Bot#15]
There is currently no check whether an override annotation already exists. It could be that in the meantime an annotation has been added and the static analysis is out of date.

**Comment by LHommeDeBat** [comment]
Added and tested check. Will be fixed in my next Pull-Request together with the optimized RenameMethod-Refactoring.

**Comment by MarvinWyrich** [comment]
Fixed with #17
