### ISSUE TITLE
Introduce a Service Layer

### ISSUE THREAD

**Issue by Simulant87** [Refactoring-Bot/Refactoring-Bot#27]
The package `de.refactoringbot.controller` and below contains business logic, but the packe and the classes are named ...Controller. In my optinion they should be named `...Service` and use the `@Service` annotation. This change makes it easier to navigate through the code, when the project follows the common layered architecture normally used in spring projects.

Also the RestControllers contain a lot of decission logic. This should also be pushed down into the Service layer to have a better encapsulation of the business logic.

**Comment by LHommeDeBat** [comment]
@Simulant87 : Can you look into https://github.com/Refactoring-Bot/Refactoring-Bot/pull/29 and check if my code is going into the right direction. I pushed most of the business logic from the Configuration and Issue Controllers into new Services. If it's fine the way it is now, I would do the same thing with the Refactoring controller.

**Comment by Simulant87** [comment]
From a first view it looks good and goes into the right direction. I think you can already continue that work on the Refactoring Controller, maybe even on a second pull request to have less changes to review at once, if the isolation of changes allows this.

Maybe I find some time on the weekend for a deeper look into it what could be improved in addition. But you don't have to wait for my review.
