### ISSUE TITLE
Create a Docker container to run the bot

### ISSUE THREAD

**Issue by xJREB** [Refactoring-Bot/Refactoring-Bot#3]
To ease dependency installation and configuration efforts, create a Docker container to run the bot.

**Comment by xJREB** [comment]
Additionally, use ENV variables to override the most important configuration parameters, like e.g. MySQL endpoint, schema, or credentials. This will greatly improve configurability and setup procedure.

**Comment by MarvinWyrich** [comment]
Related: #28 (On first start, let the bot create the DB schema, if it doesn't exist)
