### ISSUE TITLE
Issue path can't be found due to not updating code before

### ISSUE THREAD

**Issue by MarvinWyrich** [Refactoring-Bot/Refactoring-Bot#51]
When translating a sonar issue we try to find the issue in the bot's local copy of the repository. However, if the analysis results are newer than the local code, the code smell location may not be found (e.g. a new class was added to the analyzed repo). Therefore the process should be as follows (after calling `refactorWithSonarQube` in the `RefactoringController`):

1. update the code for the given config (this means to update the fork and the local copy to the newest master-version of the parent repository)
2. process issues

**Comment by MarvinWyrich** [comment]
I think it's also a good idea not to stop the refactoring completely if a location can't be found (currently an `IOException` is thrown). Instead we could continue and try to translate the next code smell. What do you think?

**Comment by LHommeDeBat** [comment]
So basically we have to keep the master of the fork up to date with the master of the repo?

**Comment by MarvinWyrich** [comment]
Yes, let's say we have the following scenario: we have a repository (R) and the bot's fork (BF). The static code analysis is running on R. When there is a new class added to R and the analysis is up-to-date, then the BF does not contain this new class but tries to find it if the analysis reports a code smell in the new class.

Therefore, the first thing we have to do is to merge changes from R into BF. Then pull BF to have an up-to-date version locally. After that we are able to find the issue path locally. Do you agree?



> Regarding the exception: Where is that exception thrown? Because if the Bot cant find the filepath inside a refactoring class, than it shouldn't lead to the cancellation of the refactoring. Other issues should still be proceeded.

In [translateSonarIssue(...)](https://github.com/Refactoring-Bot/Refactoring-Bot/blob/a993db1aab5be67d612e731910bc753babd066b5/src/main/java/de/refactoringbot/services/sonarqube/SonarQubeObjectTranslator.java#L75). If I didn't see it wrong, the exception prevents the remaining botIssues from being returned.
