### ISSUE TITLE
Enable bots to keep project dependecies updated

### ISSUE THREAD

**Issue by pethers** [Refactoring-Bot/Refactoring-Bot#61]
Both https://github.com/marketplace/dependabot-preview and https://github.com/marketplace/renovate work well and are free for open source projects. 

Use some at https://github.com/Hack23/cia/graphs/contributors, make sense for a bot project to use bots :)

**Comment by MarvinWyrich** [comment]
Thank you very much @pethers. I recently thought about getting more bot support for the project and will try the linked suggestions :)
